// storefront behavior — generated by site-gen.js
(function () {
  // scroll reveal
  const io = new IntersectionObserver(es => es.forEach(e => {
    if (e.isIntersecting) { e.target.classList.add("in"); io.unobserve(e.target); }
  }), { threshold: 0.12 });
  document.querySelectorAll(".reveal").forEach(el => io.observe(el));

  // category filter
  const pills = document.querySelectorAll(".pill");
  pills.forEach(p => p.addEventListener("click", () => {
    pills.forEach(x => x.classList.remove("active"));
    p.classList.add("active");
    const f = p.dataset.filter;
    document.querySelectorAll("#grid .card").forEach(c => {
      c.style.display = (f === "All" || c.dataset.cat === f) ? "" : "none";
    });
  }));

  // checkout
  const cfg = window.STORE_CONFIG || {};
  const live = cfg.btcpayUrl && cfg.btcpayStoreId;

  function buyLive(dir, price) {
    // BTCPay pay-button flow: hosted checkout offers Lightning AND on-chain
    const f = document.createElement("form");
    f.method = "POST";
    f.action = cfg.btcpayUrl.replace(/\/$/, "") + "/api/v1/invoices";
    const fields = {
      storeId: cfg.btcpayStoreId, price: price, currency: cfg.currency || "USD",
      orderId: dir, redirectUrl: location.origin + location.pathname.replace(/[^/]*$/, "") + "thanks.html",
    };
    for (const [k, v] of Object.entries(fields)) {
      const i = document.createElement("input");
      i.type = "hidden"; i.name = k; i.value = v; f.appendChild(i);
    }
    document.body.appendChild(f); f.submit();
  }

  const modal = document.getElementById("modal");
  let railSeed = "";

  function fakeQr(seed) {
    // decorative, deterministic pattern — clearly labeled a demo, not a real invoice
    const cv = document.getElementById("m-qr"), ctx = cv.getContext("2d");
    ctx.fillStyle = "#fff"; ctx.fillRect(0, 0, 220, 220);
    let h = 0;
    for (const ch of seed) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
    ctx.fillStyle = "#1d1d1f";
    const n = 21, cell = 200 / n;
    for (let y = 0; y < n; y++) for (let x = 0; x < n; x++) {
      h = (h * 1103515245 + 12345) >>> 0;
      if ((h >> 16) % 2) ctx.fillRect(10 + x * cell, 10 + y * cell, cell - 1, cell - 1);
    }
    [[10, 10], [10 + 15 * cell, 10], [10, 10 + 15 * cell]].forEach(([px, py]) => {
      ctx.fillRect(px, py, cell * 6, cell * 6);
      ctx.fillStyle = "#fff"; ctx.fillRect(px + cell, py + cell, cell * 4, cell * 4);
      ctx.fillStyle = "#1d1d1f"; ctx.fillRect(px + cell * 2, py + cell * 2, cell * 2, cell * 2);
    });
    ctx.fillStyle = "rgba(255,255,255,.88)"; ctx.fillRect(55, 96, 110, 28);
    ctx.fillStyle = "#f7931a"; ctx.font = "700 15px -apple-system, sans-serif";
    ctx.textAlign = "center"; ctx.fillText("DEMO", 110, 115);
  }

  function buyDemo(title, price) {
    document.getElementById("m-title").textContent = title;
    document.getElementById("m-price").textContent = "$" + price;
    railSeed = title;
    fakeQr("ln:" + railSeed);
    modal.hidden = false;
  }

  function buy(dir, title, price) {
    live ? buyLive(dir, price) : buyDemo(title, price);
  }
  document.querySelectorAll(".btn-buy[data-dir]").forEach(b => b.addEventListener("click", e => {
    e.stopPropagation();
    const { dir, title, price } = b.dataset;
    buy(dir, title, price);
  }));

  // book preview
  const BOOKS = window.BOOKS || {};
  const preview = document.getElementById("preview");
  const EB = 7.99;
  const money = n => "$" + (Number.isInteger(n) ? n : n.toFixed(2));
  function openPreview(dir) {
    const b = BOOKS[dir]; if (!b) return;
    const img = document.getElementById("pv-img");
    img.src = "covers/" + dir + ".jpg"; img.alt = b.title + " cover";
    document.getElementById("pv-cat").textContent = b.cat;
    document.getElementById("pv-title").textContent = b.title;
    document.getElementById("pv-sub").textContent = b.subtitle;
    document.getElementById("pv-headline").textContent = b.headline;
    document.getElementById("pv-copy").textContent = b.body;
    const sessions = b.dpw ? b.weeks * b.dpw : 0;
    const inside = [
      b.weeks + "-week program, mapped out week by week",
      (sessions ? sessions + " workouts" : "Every session") + " — each pre-printed as a fill-in log page",
      "Benchmark tests + a personal-record tracker",
      "A plain-English guide explaining every choice",
    ];
    document.getElementById("pv-inside").innerHTML = inside.map(t => "<li>" + t + "</li>").join("");
    const btn = document.getElementById("pv-buy");
    btn.innerHTML = '<span class="bolt">\u26A1</span> Buy ' + money(EB);
    btn.onclick = () => { preview.hidden = true; buy(dir, b.title, EB); };
    preview.hidden = false;
  }
  document.querySelectorAll("#grid .card").forEach(c => {
    c.addEventListener("click", e => { if (!e.target.closest(".btn-buy")) openPreview(c.dataset.dir); });
    c.addEventListener("keydown", e => {
      if (e.key === "Enter" || e.key === " ") { e.preventDefault(); openPreview(c.dataset.dir); }
    });
  });
  document.getElementById("pv-x").addEventListener("click", () => preview.hidden = true);
  preview.addEventListener("click", e => { if (e.target === preview) preview.hidden = true; });
  document.addEventListener("keydown", e => {
    if (e.key === "Escape") { preview.hidden = true; modal.hidden = true; }
  });

  document.querySelectorAll(".m-tab").forEach(t => t.addEventListener("click", () => {
    document.querySelectorAll(".m-tab").forEach(x => x.classList.remove("active"));
    t.classList.add("active");
    fakeQr(t.dataset.rail + ":" + railSeed);
  }));
  document.getElementById("modal-x").addEventListener("click", () => modal.hidden = true);
  modal.addEventListener("click", e => { if (e.target === modal) modal.hidden = true; });
})();

// --- private preview gate (soft, client-side) ---
(function () {
  var gate = document.getElementById("preview-gate");
  if (!gate) return;
  var PASS = "445d3e260657e8c80a96a3f676b6b4c3f7977f0ad59b15893a3303e2a3c6a57e";
  function sha256(ascii) {
    function rr(v, a) { return (v >>> a) | (v << (32 - a)); }
    var mp = Math.pow, mw = mp(2, 32), result = "";
    var words = [], bitLen = ascii.length * 8;
    var hash = sha256.h = sha256.h || [];
    var k = sha256.k = sha256.k || [];
    var pc = k.length, comp = {};
    for (var cand = 2; pc < 64; cand++) {
      if (!comp[cand]) {
        for (var ii = 0; ii < 313; ii += cand) comp[ii] = cand;
        hash[pc] = (mp(cand, .5) * mw) | 0;
        k[pc++] = (mp(cand, 1 / 3) * mw) | 0;
      }
    }
    ascii += "\x80";
    while (ascii.length % 64 - 56) ascii += "\x00";
    for (var i = 0; i < ascii.length; i++) {
      var j = ascii.charCodeAt(i);
      if (j >> 8) return "";
      words[i >> 2] |= j << ((3 - i) % 4) * 8;
    }
    words[words.length] = (bitLen / mw) | 0;
    words[words.length] = bitLen;
    for (var jj = 0; jj < words.length;) {
      var w = words.slice(jj, jj += 16), oldHash = hash;
      hash = hash.slice(0, 8);
      for (var i = 0; i < 64; i++) {
        var w15 = w[i - 15], w2 = w[i - 2];
        var a = hash[0], e = hash[4];
        var t1 = hash[7]
          + (rr(e, 6) ^ rr(e, 11) ^ rr(e, 25))
          + ((e & hash[5]) ^ (~e & hash[6]))
          + k[i]
          + (w[i] = (i < 16) ? w[i] : (
              w[i - 16]
              + (rr(w15, 7) ^ rr(w15, 18) ^ (w15 >>> 3))
              + w[i - 7]
              + (rr(w2, 17) ^ rr(w2, 19) ^ (w2 >>> 10))
            ) | 0);
        var t2 = (rr(a, 2) ^ rr(a, 13) ^ rr(a, 22))
          + ((a & hash[1]) ^ (a & hash[2]) ^ (hash[1] & hash[2]));
        hash = [(t1 + t2) | 0].concat(hash);
        hash[4] = (hash[4] + t1) | 0;
      }
      for (var i = 0; i < 8; i++) hash[i] = (hash[i] + oldHash[i]) | 0;
    }
    for (var i = 0; i < 8; i++)
      for (var j = 3; j + 1; j--) {
        var b = (hash[i] >> (j * 8)) & 255;
        result += ((b < 16) ? 0 : "") + b.toString(16);
      }
    return result;
  }
  function unlock() {
    sessionStorage.setItem("cs_preview_ok", "1");
    document.documentElement.classList.add("cs-open");
  }
  function submit() {
    var v = document.getElementById("pg-input").value || "";
    if (sha256(v) === PASS) unlock();
    else document.getElementById("pg-err").textContent = "That's not it \u2014 try again.";
  }
  document.getElementById("pg-go").addEventListener("click", submit);
  document.getElementById("pg-input").addEventListener("keydown", function (e) {
    if (e.key === "Enter") submit();
  });
})();